### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by TakenPilot** [CondeNast/quick-bus#2]
### Pre-Checks
- [x] FYI
- [x] Create an issue in [evangelism](https://github.com/CondeNast/evangelism/issues) to express intent to open source
- [ ] Attend Open Sourcing planning meeting with Open Source Working Group

### Documentation
- [x] README
- [x] CONTRIBUTING
- [x] CODE_OF_CONDUCT
- [x] LICENSE
- [x] ISSUE_TEMPLATE
- [x] PULL_REQUEST_TEMPLATE
- [x] CHANGELOG
- [ ] Announcement Blog Post

### Development
- [x] Tests
- [x] Linter
- [ ] Travis
- [x] Examples
- [x] Clear Github History

### README Checklist
- [x] Title
- [ ] Badges 
- [x] Description
- [x] Prerequisite for using software ( if any )
- [ ] Install
- [x] Example Usage
- [ ] Screenshots and GIFs
- [ ] Contributors
- [x] Conde Nast Technology Logo
- [ ] Attributions ( mention 3rd party libs used etc. )
- [ ] Benchmarks (if any)
- [ ] Prior Art (if any)

### Badges Checklist:
- [x] License Badge
- [ ] Testing Badge
- [ ] CI Badge

---
Inspired from [oss-checklist](https://github.com/scriptnull/oss-checklist)

**Comment by TakenPilot** [comment]
Closing, as we’ve gone public.
